#!/bin/bash
/init &
useradd -G $gid -o -u $uid $user
mkdir -p /home/$user/.vnc; printf "$pw" |/opt/TurboVNC/bin/vncpasswd -f > /home/$user/.vnc/passwd
chmod 600 /home/$user/.vnc/passwd
chown -R $user /home/$user/.vnc
cp /data/.xinitrc /home/$user/
chown $user /home/$user/.xinitrc 
chown $user /home/$user
runuser -l $user -c "/opt/TurboVNC/bin/vncserver -fg -autokill"
